export const ROUTE_REGISTER_REQUEST = "ROUTE_REGISTER_REQUEST";
export const ROUTE_REGISTER_SUCCESS = "ROUTE_REGISTER_SUCCESS";
export const ROUTE_REGISTER_FAIL = "ROUTE_REGISTER_FAIL";

export const ROUTE_DETAILS_REQUEST = "ROUTE_DETAILS_REQUEST";
export const ROUTE_DETAILS_SUCCESS = "ROUTE_DETAILS_SUCCESS";
export const ROUTE_DETAILS_FAIL = "ROUTE_DETAILS_FAIL";
export const ROUTE_DETAILS_RESET = "ROUTE_DETAILS_RESET";

export const ROUTE_LIST_REQUEST = "ROUTE_LIST_REQUEST";
export const ROUTE_LIST_SUCCESS = "ROUTE_LIST_SUCCESS";
export const ROUTE_LIST_FAIL = "ROUTE_LIST_FAIL";
export const ROUTE_LIST_RESET = "ROUTE_LIST_RESET";

export const ROUTE_DELETE_REQUEST = "ROUTE_DELETE_REQUEST";
export const ROUTE_DELETE_SUCCESS = "ROUTE_DELETE_SUCCESS";
export const ROUTE_DELETE_FAIL = "ROUTE_DELETE_FAIL";

export const ROUTE_UPDATE_REQUEST = "ROUTE_UPDATE_REQUEST";
export const ROUTE_UPDATE_SUCCESS = "ROUTE_UPDATE_SUCCESS";
export const ROUTE_UPDATE_FAIL = "ROUTE_UPDATE_FAIL";
export const ROUTE_UPDATE_RESET = "ROUTE_UPDATE_RESET";
