export const STOP_REGISTER_REQUEST = "STOP_REGISTER_REQUEST";
export const STOP_REGISTER_SUCCESS = "STOP_REGISTER_SUCCESS";
export const STOP_REGISTER_FAIL = "STOP_REGISTER_FAIL";
export const STOP_REGISTER_RESET = "STOP_REGISTER_RESET";

export const STOP_DETAILS_REQUEST = "STOP_DETAILS_REQUEST";
export const STOP_DETAILS_SUCCESS = "STOP_DETAILS_SUCCESS";
export const STOP_DETAILS_FAIL = "STOP_DETAILS_FAIL";
export const STOP_DETAILS_RESET = "STOP_DETAILS_RESET";

export const STOP_LIST_REQUEST = "STOP_LIST_REQUEST";
export const STOP_LIST_SUCCESS = "STOP_LIST_SUCCESS";
export const STOP_LIST_FAIL = "STOP_LIST_FAIL";
export const STOP_LIST_RESET = "STOP_LIST_RESET";

export const STOP_DELETE_REQUEST = "STOP_DELETE_REQUEST";
export const STOP_DELETE_SUCCESS = "STOP_DELETE_SUCCESS";
export const STOP_DELETE_FAIL = "STOP_DELETE_FAIL";

export const STOP_UPDATE_REQUEST = "STOP_UPDATE_REQUEST";
export const STOP_UPDATE_SUCCESS = "STOP_UPDATE_SUCCESS";
export const STOP_UPDATE_FAIL = "STOP_UPDATE_FAIL";
export const STOP_UPDATE_RESET = "STOP_UPDATE_RESET";
